### ISSUE TITLE
Question regarding lab 3

### ISSUE THREAD

**Issue by keyuchen21** [Ryota-Kawamura/Generative-AI-with-LLMs#1]
running into a cuda/cpu issue in lab 3.
any help?

![1688739583794](https://github.com/Ryota-Kawamura/Generative-AI-with-LLMs/assets/54015474/b902dc3f-bdb2-4d17-bcbf-e8f5400b5a59)

**Comment by Ryota-Kawamura** [comment]
This error occurs because the tensors are located on different devices (cuda:0 and cpu). Deep learning frameworks like TensorFlow or PyTorch require tensors to be operated on the same device.

To resolve this issue, you need to ensure that tensors are on the same device. 

If either ppo_model or toxicity_evaluator is running on the GPU (cuda), move the other one to the same device. For example, if ppo_model is on the GPU, you can move toxicity_evaluator to the GPU using the to method. For instance, toxicity_evaluator.to("cuda:0").

If the tokenizer is running on the GPU, move it to the CPU. Use tokenizer.to("cpu") to accomplish this.

If these steps don't resolve the issue, you may need to move the tensors in dataset["test"] to the same device as well.

**Comment by km5ar** [comment]
@Ryota-Kawamura 

Thank you, after I move ppo_model to cpu, it works.
plz update your script, so the small typo can be fix.

Thank you for your help a lot!


mean_after_detoxification, std_after_detoxification = evaluate_toxicity(model=ppo_model.to("cpu"), 
                                                                        toxicity_evaluator=toxicity_evaluator, 
                                                                        tokenizer=tokenizer, 
                                                                        dataset=dataset["test"], 
                                                                        num_samples=10)
print(f'toxicity [mean, std] after detox: [{mean_after_detoxification}, {std_after_detoxification}]')
